version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP port for messaging (client communication)
      - "15672:15672"     # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Mount volume to persist data
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always  # Ensure RabbitMQ restarts if it crashes or the system restarts

volumes:
  rabbitmq_data:
    driver: local
